sudo: false
language: java
services:
  - docker
cache:
  directories:
  - "$HOME/.cache"

install: true

script: mvn install

before_deploy:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PWD"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  on:
    all_branches: true
  skip_cleanup: true
