version: "3.3"

services:
  identity:
    image: hlavki/g-suite-identity-sync
    environment:
      - SLAPD_BIND_DN=cn=admin,dc=example,dc=org
      - SLAPD_BASE_DN=dc=example,dc=org
      - SLAPD_PASSWORD=changeme
      - GSUITE_DOMAIN=example.org
      - GSUITE_CLIENT_ID=*******.apps.googleusercontent.com
      - GSUITE_CLIENT_SECRET=******
    volumes:
      - identity-config:/opt/karaf/etc/identity
    depends_on:
      - ldap
    labels:
      - "traefik.port=8181"
      - "traefik.enable=true"
      - "traefik.backend=identity"
      - "traefik.frontend.rule=Host:identity.example.com"

  ldap:
    image: osixia/openldap
    ports:
      - "389:389"
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Company ltd."
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "changeme"
      LDAP_CONFIG_PASSWORD: "changeme"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d

  traefik:
    image: traefik
    command: -c /dev/null --api --docker --docker.domain=example.com --logLevel=DEBUG
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  identity-config:
  ldap-config:
  ldap-data:
